export const S = {
  sessionCreated: "session:created",
  sessionList: "session:list",
  sessionUpdated: "session:updated",
  sessionHung: "session:hung",
  sessionEnded: "session:ended",
  migrationStarted: "migration:started",
  migrationProgress: "migration:progress",
  migrationTransferProgress: "migration:transfer-progress",
  migrationStep: "migration:step",
  migrationCompleted: "migration:completed",
  migrationFailed: "migration:failed",
  machineList: "machine:list",
  machineUpdated: "machine:updated",
  logEntry: "log:entry",
  sessionLaunch: "session:launch",
  sessionMigrate: "session:migrate",
  sessionKill: "session:kill",
  sessionCheckpoint: "session:checkpoint",
};
